-- Supabase configuration seed generated on 2026-02-23T08:55:17Z
BEGIN;

CREATE TABLE IF NOT EXISTS public.app_config (
    key_path text PRIMARY KEY,
    value jsonb NOT NULL
);

INSERT INTO public.app_config (key_path, value) VALUES
  ('api.aeroapi.monthly_budget_per_key_usd', '5.0'::jsonb),
  ('api.aeroapi.usage_cache_ttl_seconds', '600'::jsonb),
  ('api.airport_icao', '"LEMD"'::jsonb),
  ('api.preloaded_data', 'true'::jsonb),
  ('api.time_range_hours', '2'::jsonb),
  ('database.airport_icao', '"LEMD"'::jsonb),
  ('database.provider', '"supabase"'::jsonb),
  ('execution.interval', '6600'::jsonb),
  ('image_finder.allowed_image_hosts', '["jetphotos.com", "cdn.jetphotos.com", "planespotters.net", "plnspttrs.net", "t.plnspttrs.net"]'::jsonb),
  ('image_finder.base_delay_seconds', '1.5'::jsonb),
  ('image_finder.download_max_bytes', '5242880'::jsonb),
  ('image_finder.download_timeout_seconds', '30'::jsonb),
  ('image_finder.enabled', 'true'::jsonb),
  ('image_finder.jitter_seconds', '0.5'::jsonb),
  ('image_finder.max_delay_seconds', '10'::jsonb),
  ('image_finder.max_retries', '3'::jsonb),
  ('image_finder.negative_cache_ttl_seconds', '1200'::jsonb),
  ('image_finder.positive_cache_ttl_seconds', '21600'::jsonb),
  ('image_finder.provider_cooldown_seconds', '600'::jsonb),
  ('image_finder.providers', '["planespotters", "jetphotos"]'::jsonb),
  ('image_finder.request_timeout_seconds', '15'::jsonb),
  ('image_finder.user_agent', '"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"'::jsonb),
  ('logging.log_file', '"logs/lemd_spotter.log"'::jsonb),
  ('logging.log_level', '"DEBUG"'::jsonb),
  ('logging.log_rotation', '"10 MB"'::jsonb),
  ('logging.warning_log_file', '"logs/lemd_spotter_warning.log"'::jsonb),
  ('message_policy.defaults.fallback_order', '["long", "medium", "short"]'::jsonb),
  ('message_policy.defaults.overflow_action', '"block"'::jsonb),
  ('message_policy.defaults.preferred_profile', '"long"'::jsonb),
  ('message_policy.platform_limits.bluesky', '300'::jsonb),
  ('message_policy.platform_limits.instagram', '2200'::jsonb),
  ('message_policy.platform_limits.linkedin', '3000'::jsonb),
  ('message_policy.platform_limits.telegram_caption', '1024'::jsonb),
  ('message_policy.platform_limits.telegram_text', '4096'::jsonb),
  ('message_policy.platform_limits.threads', '500'::jsonb),
  ('message_policy.platform_limits.twitter', '280'::jsonb),
  ('message_policy.platforms.bluesky.preferred_profile', '"short"'::jsonb),
  ('message_policy.platforms.instagram.preferred_profile', '"medium"'::jsonb),
  ('message_policy.platforms.linkedin.preferred_profile', '"medium"'::jsonb),
  ('message_policy.platforms.telegram.preferred_profile', '"long"'::jsonb),
  ('message_policy.platforms.threads.preferred_profile', '"medium"'::jsonb),
  ('message_policy.platforms.twitter.preferred_profile', '"short"'::jsonb),
  ('message_templates.profiles.long', '"Flight Information:\n\nFlight: {flight_label}\nRegistration: {registration}\nAircraft: {aircraft}\nAirline: {airline_name} ({airline_code})\nRoute: {origin_name} ({origin_icao}) -> {destination_name} ({destination_icao})\nScheduled Time: {scheduled_time}\nTerminal: {terminal}\nInteresting: {long_interesting}{long_diverted}\n\nCheck all our socials in https://linktr.ee/ctrl_plataforma"'::jsonb),
  ('message_templates.profiles.medium', '"Flight: {flight_label}\nReg: {registration}\nAircraft: {aircraft}\nRoute: {origin_icao}->{destination_icao} ({origin_name} to {destination_name})\nTime: {scheduled_time}\nTerminal: {terminal}\nAirline: {airline_name} ({airline_code})\nInteresting: {medium_interesting}{medium_diverted}\nFR24: {flight_url}\nPowered by Plane Spotter"'::jsonb),
  ('message_templates.profiles.short', '"Flight: {flight_label}\nRegistration: {registration}\nAircraft: {aircraft}\nAirline: {airline_name} ({airline_code})\nRoute: {origin_name} ({origin_icao}) -> {destination_name} ({destination_icao})\nScheduled Time: {scheduled_time}\nTerminal: {terminal}\nInteresting: {short_interesting}{short_diverted}\nFR24: {flight_url}"'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.aircraft', '60'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.airline_code', '8'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.airline_name', '50'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.destination_icao', '4'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.destination_name', '50'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.diverted_text', '32'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.flight_label', '40'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.flight_slug', '56'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.flight_url', '95'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.interesting_text', '140'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.long_diverted', '90'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.long_interesting', '220'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.medium_diverted', '48'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.medium_interesting', '170'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.origin_icao', '4'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.origin_name', '50'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.registration', '12'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.scheduled_time', '16'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.short_diverted', '11'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.short_interesting', '120'::jsonb),
  ('message_templates.validation.placeholder_max_chars.long.terminal', '10'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.aircraft', '42'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.airline_code', '8'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.airline_name', '40'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.destination_icao', '4'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.destination_name', '32'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.diverted_text', '24'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.flight_label', '32'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.flight_slug', '48'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.flight_url', '95'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.interesting_text', '90'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.long_diverted', '64'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.long_interesting', '160'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.medium_diverted', '40'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.medium_interesting', '130'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.origin_icao', '4'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.origin_name', '32'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.registration', '12'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.scheduled_time', '16'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.short_diverted', '11'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.short_interesting', '100'::jsonb),
  ('message_templates.validation.placeholder_max_chars.medium.terminal', '10'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.aircraft', '28'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.airline_code', '8'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.airline_name', '30'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.destination_icao', '4'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.destination_name', '24'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.diverted_text', '11'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.flight_label', '24'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.flight_slug', '40'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.flight_url', '95'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.interesting_text', '64'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.long_diverted', '48'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.long_interesting', '120'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.medium_diverted', '32'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.medium_interesting', '96'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.origin_icao', '4'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.origin_name', '24'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.registration', '12'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.scheduled_time', '16'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.short_diverted', '11'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.short_interesting', '60'::jsonb),
  ('message_templates.validation.placeholder_max_chars.short.terminal', '8'::jsonb),
  ('message_templates.validation.profile_max_chars.long', '2500'::jsonb),
  ('message_templates.validation.profile_max_chars.medium', '1200'::jsonb),
  ('message_templates.validation.profile_max_chars.short', '600'::jsonb),
  ('platform_settings.bluesky.registration_link_enabled', 'true'::jsonb),
  ('platform_settings.telegram.notifications_enabled', 'true'::jsonb),
  ('platform_settings.telegram.registration_link_enabled', 'true'::jsonb),
  ('social_networks.bluesky', 'true'::jsonb),
  ('social_networks.instagram', 'false'::jsonb),
  ('social_networks.linkedin', 'false'::jsonb),
  ('social_networks.telegram', 'true'::jsonb),
  ('social_networks.threads', 'false'::jsonb),
  ('social_networks.twitter', 'false'::jsonb),
  ('usage_monitoring.db_path', '"database/usage_metrics.db"'::jsonb),
  ('usage_monitoring.enabled', 'true'::jsonb),
  ('usage_monitoring.x.default_cost_per_call_usd', '0.01'::jsonb),
  ('usage_monitoring.x.endpoint_costs_usd.GET /2/usage/tweets', '0.01'::jsonb),
  ('usage_monitoring.x.endpoint_costs_usd.POST /1.1/media/upload.json', '0.01'::jsonb),
  ('usage_monitoring.x.endpoint_costs_usd.POST /2/tweets', '0.01'::jsonb),
  ('usage_monitoring.x.enforce_budget', 'true'::jsonb),
  ('usage_monitoring.x.monthly_budget_usd', '10.0'::jsonb)
ON CONFLICT (key_path) DO UPDATE SET value = EXCLUDED.value;

COMMIT;
